# Generated by Django 2.0.7 on 2018-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181118_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quote',
            field=models.CharField(default='Lorem ipsum dolor lalala hahaha', max_length=255),
            preserve_default=False,
        ),
    ]
