# Generated by Django 2.0.7 on 2018-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181118_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='coryrin'),
            preserve_default=False,
        ),
    ]
