# Generated by Django 2.0.7 on 2019-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190126_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
