# Generated by Django 2.0.7 on 2018-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumboard',
            name='slug',
            field=models.SlugField(default='general'),
            preserve_default=False,
        ),
    ]
