# Generated by Django 2.0.7 on 2018-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_forumboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumboard',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
