# Generated by Django 2.0.7 on 2018-07-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_post_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
