# Generated by Django 2.0.7 on 2018-12-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20181118_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
