# Generated by Django 2.0.7 on 2019-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_postcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
