# Generated by Django 2.0.7 on 2019-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20190129_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
