# Generated by Django 2.0.7 on 2019-02-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_post_body_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-views'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_html',
        ),
    ]
